add condition for bulk queries upload to cosmos

diff --git a/resources/cosmos-upload b/resources/cosmos-upload
--- a/resources/cosmos-upload
+++ b/resources/cosmos-upload
@@ -3,26 +3,55 @@
 set -e
 projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"
 
-echo "Enter CRN (default 1):"
-read -r input_crn
-crn=${input_crn:-1}
-
-echo "Enter SBI (default 1):"
-read -r input_sbi
-sbi=${input_sbi:-1}
-
-echo "Enter Database Name (default 'ffc-sfd-customer-receiver-messages'):"
+echo "Enter Database Name (default 'ffc-sfd-customer-receiver-messages'. Other options include 'ffc-sfd-customer-receiver-queries'):"
 read -r input_database
 database=${input_database:-'ffc-sfd-customer-receiver-messages'}
 
-echo "Enter Container Name (default 'messages-container'):"
-read -r input_container
-container=${input_container:-'messages-container'}
+if [ "$database" == "ffc-sfd-customer-receiver-messages" ]; then
 
-echo "Enter Quantity (default 1):"
-read -r input_quantity
-quantity=${input_quantity:-1}
+  echo "Enter CRN (default 1):"
+  read -r input_crn
+  crn=${input_crn:-1}
 
-cd "${projectRoot}"
+  echo "Enter SBI (default 1):"
+  read -r input_sbi
+  sbi=${input_sbi:-1}
 
-node resources/upload.js "$crn" "$sbi" "$database" "$container" "$quantity"
+  echo "Enter Container Name (default 'messages-container'):"
+  read -r input_container
+  container=${input_container:-'messages-container'}
+
+  echo "Enter Quantity (default 1):"
+  read -r input_quantity
+  quantity=${input_quantity:-1}
+
+  cd "${projectRoot}"
+
+  node resources/upload-messages.js "$crn" "$sbi" "$database" "$container" "$quantity"
+
+elif [ "$database" == "ffc-sfd-customer-receiver-queries" ]; then
+
+  echo "Enter CRN (default 1):"
+  read -r input_crn
+  crn=${input_crn:-1}
+
+  echo "Enter SBI (default 1):"
+  read -r input_sbi
+  sbi=${input_sbi:-1}
+
+  echo "Enter Container Name (default 'queries-container'):"
+  read -r input_container
+  container=${input_container:-'queries-container'}
+
+  echo "Enter Quantity (default 1):"
+  read -r input_quantity
+  quantity=${input_quantity:-1}
+
+  cd "${projectRoot}"
+
+  node resources/upload-queries.js "$name" "$crn" "$sbi" "$database" "$container" "$quantity"
+
+else
+  echo "Invalid database name. Please enter either 'ffc-sfd-customer-receiver-messages' or 'ffc-sfd-customer-receiver-queries'."
+  exit 1
+fi
